### PR TITLE
Updates based on today's meeting

### PR DESCRIPTION
**Pull request by pb-cdunn**
Should we also add max read-lengths? And maybe means for polymerase and seed reads? And maybe delete "read count" for pre-assembly, since it is derivable from mean and #bases?

### CODE REVIEW

**Comment by pbjd** [comment]
Much of the information is derivable, but there is value in explicitly displaying certain things.  I would add coverage for polymerase reads as well.   Although I just realized that these should probably say 'Subread', not 'polymerase read'.

**Comment by pb-cdunn** [comment]
"Subread Reads"? That's kinda weird. How about "Raw Reads"?

**Comment by pbjd** [comment]
Just Subreads, no need for the extra 'Reads'.   I'll submit a pull request once it's finalized.

**Comment by pb-cdunn** [comment]
Could we at least use something consistent, like

* "subreads"
* "seedreads"
* "preads" or "preassemblyreads"

In other words, drop the space between type and the word "reads" for the other names as well.

> I'll submit a pull request once it's finalized.

Ok. I'll let you make the changes.

**Pull request merged**
