### PR TITLE
Remove L*.las files created for large genomes.

### PR DESCRIPTION
**Pull request by ylipacbio**
SAT-567, SAT-559

### CODE REVIEW

**Comment by pb-cdunn** [comment]
You have not understood my point yet. If it's ok to remove `raw_reads.*.las` for small genomes, then it's ok to remove `L1.*.*.las` for large genomes at the same spot in the workflow. I do not want different behavior for different genome sizes.

**Comment by pb-jchin** [comment]
I might be out of context. If a user want to do diploid genome unzip, we will need those final "*.las" files.

**Comment by ylipacbio** [comment]
What are the final "*.las" files?

**Comment by pb-jchin** [comment]
> What are the final "*.las" files?

`raw_reads.[0-9]+.las`

**Comment by ylipacbio** [comment]
So raw_reads.[0-9]+.las and L*.las might be needed for unzipping?

**Comment by pb-cdunn** [comment]
Only `raw_reads.*.las`. The L1 files are always intermediate.

**Comment by pb-jchin** [comment]
Ideally, we should keep those files and use another simple utility to clean them us as an user option.

**Comment by ylipacbio** [comment]
Got it, only `raw_reads.*.las` are needed for unzipping.

**Comment by ylipacbio** [comment]
The `raw_reads.*.raw_reads.*.las`, `L1.*.las` and `preads.*.preads.*.las` almost took ~4.5TB space for HGAP4 on rice genome, that's why we need to clean up these intermediate files. See https://jira.pacificbiosciences.com/browse/SAT-559 for details.

We can keep useful final las files (e.g., `raw_reads.[0-9]+.las`) by default for unzipping. Please comment on https://jira.pacificbiosciences.com/browse/SAT-567 for discussion.

**Comment by pb-cdunn** [comment]
I don't remember the difference between large and small genomes. We want to keep whatever is not removed by HPC.daligner. Just add back the `rm` lines, following symlinks. That will remove 3.0T of 4.5T.

The remaining 1.5T can be removed optionally after draft assembly or unzip.

This change is not needed at all. The previous change is fine, since we are not running unzip after the hgap4 pipeline.

**Comment by pb-jchin** [comment]
> This change is not needed at all. The previous change is fine, since we are not running unzip after the hgap4 pipeline.

We need to revisit this. (and I have chatted with a couple of people.)  However, the discussion about this is not in this scope in GitHub.

**Pull request closed without merging**
