### PR TITLE
change some preassembly report metric types from float to int

### PR DESCRIPTION
**Pull request by ben-lerch**

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Hmmm. Why not move that function into pbreports? Make the result just a string, the JSON-encoded Report.

**Comment by pb-cdunn** [comment]
Reverting. We need to discuss this.

**Comment by pb-cdunn** [comment]
Ben, I saved your commit on the `pull-29` branch. You can resubmit it for the purpose of API discussion. Or just wait until the next Sprint.

**Comment by pbjd** [comment]
Agreed, this should happen at the display layer.

**Comment by pb-cdunn** [comment]
@pbjd,

My point is that all the code dealing with `Report` and "attributes" should be near the new spec-files. That way, if one is changed, the other can be changed in sync easily. We want to specify only data.

Beyond that, I'd like to reduce coupling. We really only need to receive the JSON-encoded content of the Report, not the Report object itself. We will simply write that to disk.I'd like to make it simple to add new fields. Think about the order of changes. The goal is to be able to add something by first changing only *our* repo, and nothing should break.

**Comment by pb-cdunn** [comment]
@pbjd,

My point is that all the code dealing with `Report` and "attributes" should be near the new spec-files. That way, if one is changed, the other can be changed in sync easily. We want to specify only data.

Beyond that, I'd like to reduce coupling. We really only need to receive the JSON-encoded content of the Report, not the Report object itself. We will simply write that to disk.

And I want to simplify future modifications. It should be a simple process to add new fields. Think about the order of changes. The goal is to be able to add something by first changing only *our* repo. Nothing should break if we provide a *new*, previously unseen field to this new API call. Later, whenever Ben or someone else has time, the spec-file can be changed to consume the extra field. That way, 2 different teams can make these 2 separate changes whenever it becomes convenient. Removing a field could happen out-of-sync too, just in the reverse order.

And I'm saying that this change is **trivial**. It doesn't take much time. We just need a brief discussion.

**Pull request merged**
